# Name of the big-bear-wordpress application
name: wordpress

# Service definitions for the wordpress application
services:
  # Service definition for the main application
  app:
    # Docker image to use for the application
    image: wordpress:6.7.1
    # Port mapping for the application
    ports:
      - 8080:80
    # Environment variables for the application
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: umbrel
      WORDPRESS_DB_PASSWORD: umbrel
      WORDPRESS_DB_NAME: wordpress
    # Volume mapping for the application
    volumes:
      - /DATA/AppData/$AppID/html:/var/www/html
    # Service dependencies for the application
    depends_on:
      - db
    x-casaos: # CasaOS specific configuration
      envs:
        - container: WORDPRESS_DB_HOST
          description:
            en_us: Database host
        - container: WORDPRESS_DB_USER
          description:
            en_us: Database user
        - container: WORDPRESS_DB_PASSWORD
          description:
            en_us: Database password
        - container: WORDPRESS_DB_NAME
          description:
            en_us: Database name
      volumes:
        - container: /var/www/html
          description:
            en_us: "Container Path: /var/www/html"
      ports:
        - container: "80"
          description:
            en_us: "Container Port: 80"

  # Service definition for the database
  db:
    # Docker image to use for the database
    image: mysql:5.7
    # Environment variables for the database
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: umbrel
      MYSQL_PASSWORD: umbrel
      MYSQL_ROOT_PASSWORD: umbrel
    # Volume mapping for the database
    volumes:
      - /DATA/AppData/$AppID/mysql:/var/lib/mysql
    x-casaos: # CasaOS specific configuration
      envs:
        - container: MYSQL_DATABASE
          description:
            en_us: Database name
        - container: MYSQL_USER
          description:
            en_us: Database user
        - container: MYSQL_PASSWORD
          description:
            en_us: Database password
        - container: MYSQL_ROOT_PASSWORD
          description:
            en_us: Database root password
      volumes:
        - container: /var/lib/mysql
          description:
            en_us: "Container Path: /var/lib/mysql"
      ports:
        - container: "3306"
          description:
            en_us: "Container Port: 3306"
